# Generated by Django 3.2.5 on 2021-08-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='某用户', max_length=20)),
                ('saying', models.TextField(default='尚未留言')),
            ],
            options={
                'db_table': 'circle',
            },
        ),
    ]
