# Generated by Django 3.2.5 on 2021-08-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
